#!/usr/bin/env node
// update_groups.ts — Fetch the latest ISBN registration ranges from
// isbn-international.org and regenerate src/groups.ts

import { writeFile } from 'node:fs/promises'
import { parseStringPromise } from 'xml2js'
import type { Groups } from '../src/types.js'

const domain = 'https://www.isbn-international.org'
const url = `${domain}/bl_proxy/GetRangeInformations`

const params = new URLSearchParams({
  format: '1',
  language: 'en',
  translatedTexts: 'Printed;Last Change',
})

const getFileUrl = async (): Promise<string> => {
  const res = await fetch(url, { method: 'POST', body: params })
  const body = await res.json()
  const { filename, value } = body.result
  return `${domain}/download_range/${value}/${filename}`
}

// biome-ignore lint/suspicious/noExplicitAny: xml2js produces untyped nested arrays
type RawPrefix = any

const groupRanges = (prefixData: RawPrefix): Array<[string, string]> =>
  prefixData.Rules[0].Rule.filter((rule: RawPrefix) => rule.Length[0] !== '0').map((rule: RawPrefix) => {
    const length = Number(rule.Length[0])
    const range = rule.Range[0].toString().split('-')
    const start = range[0].substring(0, length)
    const end = range[1].substring(0, length)
    return [start, end] as [string, string]
  })

const getGroups = (result: RawPrefix): Groups => {
  const prefixesData = result.ISBNRangeMessage.RegistrationGroups[0].Group
  const groups: Groups = {}
  for (const prefixData of prefixesData) {
    const groupKey = prefixData.Prefix[0]
    groups[groupKey] = {
      name: prefixData.Agency[0].trim(),
      ranges: groupRanges(prefixData),
    }
  }
  return groups
}

const formatTsFile = (groups: Groups): string => {
  const content = JSON.stringify(groups, null, 2)
    .replace(/'/g, "\\'") // escape any single quotes
    .replace(/"/g, "'") // use single quotes
    .replace(/'(name|ranges)'/g, '$1') // unquote known keys

  return [
    '// Generated by scripts/update_groups.ts',
    "import type { Groups } from './types.js'",
    '',
    `const groups: Groups = ${content}`,
    '',
    'export default groups',
    '',
  ].join('\n')
}

console.log('Requesting XML ranges file...')
const fileUrl = await getFileUrl()
console.log(`Downloading ${fileUrl}...`)
const res = await fetch(fileUrl)
const xml = await res.text()
const parsed = await parseStringPromise(xml)
const fileContent = formatTsFile(getGroups(parsed))
await writeFile('./src/groups.ts', fileContent)
console.log('File saved: ./src/groups.ts')
