name: Auto-update groups data

on:
  schedule:
    # Every first of the month at 10:00
    - cron:  '0 10 1 * *'

# See https://docs.github.com/fr/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions:
  id-token: write # Required for OIDC, see https://docs.npmjs.com/trusted-publishers
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci --no-audit
      - run: npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci --no-audit
      - run: npm run update-groups
      - run: |
          echo 'Set git config user.email...'
          git config --global user.email "devnull@inventaire.io"
          echo 'Set git config user.name...'
          git config --global user.name "Auto-Update groups"
          echo 'Stage files...'
          git add ./lib/groups.js
          echo 'Commit files...'
          git commit -m 'Auto-update groups'
          echo 'Increment patch version number...'
          npm version patch
          echo 'Pushing commits to repo...'
          git push origin main
          echo 'Pushing tags to repo...'
          git push origin main --tags
          echo 'Publish on NPM...'
          npm publish
          echo 'Done!'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
